# Generated by Django 5.1.3 on 2024-11-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('year_made', models.IntegerField(max_length=100)),
            ],
        ),
    ]
