# Generated by Django 5.1.3 on 2024-11-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_camera_year_made_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Analog'), ('D', 'Digital')], default='A', max_length=1)),
                ('color', models.BooleanField()),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(default=None, max_length=100)),
                ('speed', models.IntegerField(default=None)),
            ],
        ),
    ]
