# Generated by Django 5.1.3 on 2024-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_camera_films'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='upload',
            name='date',
            field=models.DateField(verbose_name='Upload Date'),
        ),
    ]
